

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking_lot?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ITAtest666.
  jpa:
    hibernate:
      ddl-auto: validate
  fiyway:
    enabled: true
  profiles:
    active: local

server:
  port: 8088